name: Build and Push

on:
  release:
    types: [published]
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        tester: [testmail, testload, s3-tester]
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build
        run: |
          export DOCKER_IMAGE_URL=ghcr.io/${{ github.repository_owner }}/${{ matrix.tester }}
          docker build --platform=linux/amd64 -f dockerfiles/${{ matrix.tester }}/Dockerfile -t ${DOCKER_IMAGE_URL}:latest -t $DOCKER_IMAGE_URL:${GITHUB_SHA::8} .

      - name: Push
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          export DOCKER_IMAGE_URL=ghcr.io/${{ github.repository_owner }}/${{ matrix.tester }}
          docker push $DOCKER_IMAGE_URL:latest
          docker push $DOCKER_IMAGE_URL:${GITHUB_SHA::8}
